# Generated by Django 5.2.15 on 2026-06-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='tickets.order'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('general', 'General help'), ('cancel_order', 'Cancel order')], default='general', max_length=30),
        ),
    ]
