# Generated by Django 5.2.15 on 2026-06-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supportrequest_order_supportrequest_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Cancellation request',
                'verbose_name_plural': 'Cancellation requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.supportrequest',),
        ),
    ]
