# Generated by Django 5.2.15 on 2026-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_returned',
            field=models.BooleanField(default=False),
        ),
    ]
