# Generated by Django 5.2.15 on 2026-06-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_order_stock_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
